name:                shecretbox
version:             0.0.1
description:         crypto_box and crypto_secret_box implementations based on
                     cryptonite primitives. See the README on GitHub for more
                     information.
                     <https://github.com/yutotakano/shecretbox>
synopsis:            crypto_box and crypto_secret_box implementations based on
                     cryptonite primitives.
github:              "yutotakano/shecretbox"
license:             BSD-3
author:              Yuto Takano
maintainer:          "moa17stock@gmail.com"
copyright:           "2022 Yuto Takano"
category:            Cryptography
extra-source-files:
- README.md
- ChangeLog.md

default-extensions:  OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- cryptonite
- bytestring
- memory

library:
  source-dirs: src
  exposed-modules:
  - Crypto.Box
  - Crypto.SecretBox

tests:
  shecretbox-test:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
    - bytestring
    - shecretbox
    - hspec
